# Generated by Django 4.0.4 on 2022-07-01 18:21

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', multiselectfield.db.fields.MultiSelectField(choices=[('Teacher', 'Teacher'), ('student', 'student'), ('other', 'other')], default='-', max_length=21)),
            ],
        ),
    ]
