# Generated by Django 4.0.4 on 2022-07-01 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='Name',
            field=models.CharField(default='-', max_length=25),
        ),
        migrations.AddField(
            model_name='data',
            name='facultymailid',
            field=models.CharField(default='-', max_length=40),
        ),
        migrations.AddField(
            model_name='data',
            name='facultyname',
            field=models.CharField(default='-', max_length=30),
        ),
        migrations.AddField(
            model_name='data',
            name='studentid',
            field=models.CharField(default='-', max_length=25),
        ),
        migrations.AddField(
            model_name='data',
            name='studentmail',
            field=models.CharField(default='-', max_length=40),
        ),
    ]
