# Generated by Django 4.0.4 on 2022-07-01 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_data_name_data_facultymailid_data_facultyname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='studentmail',
        ),
    ]
