# Generated by Django 4.0.4 on 2022-07-02 08:42

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_data_studentmail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='x',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Facultyadvisor', 'Facultyadvisor'), ('Warden', 'Warden'), ('Student-life coordinator', 'Student-life coordinator')], default='-', max_length=46),
        ),
    ]
