# Generated by Django 4.0.4 on 2022-07-03 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_cont'),
    ]

    operations = [
        migrations.AddField(
            model_name='cont',
            name='facultyid',
            field=models.CharField(default='-', max_length=20),
        ),
    ]
