# Generated by Django 4.0.4 on 2022-07-02 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='requesting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starttime', models.DateTimeField()),
                ('endtime', models.DateTimeField()),
                ('reason', models.TextField()),
                ('days', models.IntegerField()),
                ('email', models.CharField(max_length=30)),
                ('isfaculty', models.CharField(default='no', max_length=12)),
                ('iswarden', models.CharField(default='no', max_length=12)),
                ('islifecoordinator', models.CharField(default='no', max_length=12)),
            ],
        ),
    ]
