# Generated by Django 4.0.4 on 2022-07-02 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_requesting_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesting',
            name='faculty',
            field=models.CharField(default='-', max_length=20),
        ),
    ]
