# Generated by Django 4.0.4 on 2022-07-02 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_requesting_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesting',
            name='coordinate',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='requesting',
            name='warden',
            field=models.CharField(default='-', max_length=20),
        ),
    ]
