# Generated by Django 4.0.4 on 2022-07-02 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_requesting_coordinate_requesting_warden'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesting',
            name='cord',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='requesting',
            name='ward',
            field=models.CharField(default='-', max_length=20),
        ),
    ]
